### ISSUE TITLE
Allow setting of different executors per command in the `npm` role

### ISSUE THREAD

**Issue by gregharvey** [codeenigma/ansible-deploy#607]
We should refactor this role so it accepts commands like this:

```yaml
npm:
  commands:
    - executor: npm
      command: install
    - executor: npx
      command: gulp css
```

This way a developer can call different executors without having to invoke the role over and over with passed variables.
